# Generated by Django 3.0.1 on 2020-01-01 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0002_auto_20200101_2338'),
        ('case', '0001_initial'),
        ('institution', '0002_auto_20200101_2338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userref',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='case',
            name='auditedInstitution',
            field=models.ManyToManyField(to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='case',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='matrix',
            field=models.ManyToManyField(to='dictionary.Dictionary'),
        ),
        migrations.AddField(
            model_name='case',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='responsibleUser',
            field=models.ManyToManyField(related_name='case_responsibleUser', through='case.UserRef', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserRefProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('case.userref',),
        ),
        migrations.AddField(
            model_name='case',
            name='notifiedUser',
            field=models.ManyToManyField(related_name='case_notifiedUser', through='case.UserRefProxy', to=settings.AUTH_USER_MODEL),
        ),
    ]
