# Generated by Django 3.0.1 on 2020-01-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('case', '0003_auto_20200101_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'case'), ('model', 'Case')), models.Q(('app_label', 'api'), ('model', 'Letter')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
