# Generated by Django 3.0.1 on 2020-01-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20200101_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
