# Generated by Django 3.0.1 on 2020-01-01 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('WHOSE', 'whose case'), ('WSCOPE', 'Jaki zakres sprawy'), ('ISCOPE', 'Bezczynność w jakim zakresie'), ('DSCOPE', 'Decyzja w jakim zakresie'), ('INFOT', 'Informacja udzielona w którym momencie'), ('STATUS', 'Status')], max_length=100)),
                ('minItems', models.IntegerField(default=1)),
                ('maxItems', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_createdBy', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dictionary_modifiedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Required',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.BooleanField()),
                ('voivodeship', models.BooleanField()),
                ('flat_no', models.BooleanField()),
                ('street', models.BooleanField()),
                ('postal_code', models.BooleanField()),
                ('house_no', models.BooleanField()),
                ('email', models.BooleanField()),
                ('epuap', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_field', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='flat_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AddressData'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='administrativeUnit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AdministrativeUnit'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='institution_createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institution',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='institution_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('color', models.CharField(default='0000000000', max_length=9)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_createdBy', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_modifiedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DictValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('FED', 'fedrowanie'), ('FAX', 'faks'), ('CUS', 'od klienta'), ('MEC', 'mecenas zewnętrzny'), ('PER', 'dostarczenie osobiste'), ('EMAIL', 'email'), ('POST', 'poczta tradycyjna'), ('EPUAP', 'epuap')], default='EMAIL', max_length=5)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='channel_createdBy', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='channel_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('required', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Required')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('letterCount', models.IntegerField(default=0)),
                ('noteCount', models.IntegerField(default=0)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_createdBy', to=settings.AUTH_USER_MODEL)),
                ('matrix', models.ManyToManyField(to='api.Dictionary')),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_modifiedBy', to=settings.AUTH_USER_MODEL)),
                ('notifiedUser', models.ManyToManyField(related_name='case_notifiedUser', to='api.UserRef')),
                ('responsibleUser', models.ManyToManyField(related_name='case_responsibleUser', to='api.UserRef')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tag')),
            ],
        ),
    ]
