# Generated by Django 3.0.1 on 2020-01-02 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0003_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_field', models.CharField(max_length=256)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'case'), ('model', 'Case')), models.Q(('app_label', 'api'), ('model', 'Letter')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.AlterField(
            model_name='tagnamespace',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tagnamespace_createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tagnamespace',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tagnamespace_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
